### ISSUE TITLE
Policy/Target network

### ISSUE THREAD

**Issue by NMO13** [zeroize318/tetris_ai#4]
Very nice project!
I have one question: I analyzed your code and I think that you don't use a separate policy and target network. Is that right or am I missing something?
Maybe that would shorten the training time.

**Comment by zeroize318** [comment]
Thanks!
It's been 3 years since the last time I did anything about RL so I might have forgotten or be wrong about many important concepts.
Are we talking about Double DQN, or completely different networks for action policy and state?
For Double DQN, I believe my code implements a delay between target and actions. It explores thousands of states based on old policy, calculate targets and then update the networks. I haven't encountered any instability, so this should be fine.
For the latter topic, my code is a pure DQN and it takes action solely from choosing the best state. It does not have a separate network for actions.

**Comment by NMO13** [comment]
That's quite some time ago.
I mean the thing where two networks are initialized with the same parameters. One is used for policy and one for the target. The policy network is updated via SGD and the target weights are copied from the policy from time to time.
Well it works but I am not sure why.
The other things that gives me even more headache is the fact that you just use V(s) and not Q(s, a). So actions are not taken into account at all and it still works.
